server:
  port: 8766
security.basic.enabled: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

management:
  security:
    enabled: false