server:
  port: 9998

security:
  user:
    name: admin
    password: 123456

management:
  port: 9999

spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        #location: monitor-service
        location: http://192.168.7.160:8989/hystrix.stream
