eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: ${info.project.version:}
      management.context-path: ${management.endpoints.web.base-path}
      management.port: ${management.server.port}

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['*']
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true
    
spring:
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      percentage: 1

zipkin:
  rabbitmq:
    queue: zipkin