eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      management.context-path: /management
      management.port: ${management.port}

management:
  context-path: /management
  security:
    enabled: false

feign:
  hystrix:
    enabled: true
    
spring:
  sleuth:
    sampler:
      percentage: 1